### ISSUE TITLE
Sha256 Mismatch in Homebrew Cask

### ISSUE THREAD

**Issue by apolishch** [facebook/idb#441]
When installing from Homebrew via
brew tap facebook/fb
export CODE_SIGNING_REQUIRED=NO && brew install fbsimctl

I get the following error message:
```Error: SHA256 mismatch
Expected: 5d2ed56047f2b4b3f5f0804545c6730876be2372a834e70bc88a4cb9d4253e19
Actual: 4a8bb8aed15f756aeb57e4a1f8724e40a3dfaa27740ae1644021386ab64bd9fb
Archive: /Users/courtenay/Library/Caches/Homebrew/fbsimctl-0.4.0.0```

And the install fails

**Comment by pachun** [comment]
I am see this, too.

macOS Sierra version 10.12.2

homebrew version 1.3.2 (`Homebrew/homebrew-core (git revision f0b9f; last commit 2017-09-13)`)

Is there an alternate way to install this? I'd really like to have it, even if I can't use homebrew.

**Comment by pachun** [comment]
I was trying to install FBSimulatorControl in order to use [Detox, the README for which, specifically says not to use the `--HEAD` option](https://github.com/wix/detox/blob/master/docs/Introduction.GettingStarted.md). Based on your comment, it looks like you're doing the same.

I got the same SHA mismatch error as you, @apolishch, until I tried with `--HEAD`, as this readme instructs (`export CODE_SIGNING_REQUIRED=NO && brew install fbsimctl --HEAD`)

When I tried adding back `--HEAD` (the consequence of which is that I guess we're using an "unstable" version of fbsimctl - according to the Detox README) [I got the an error, the solution to which is written here](https://github.com/facebook/FBSimulatorControl/issues/432#issuecomment-320965657).

After running those two commands, `export CODE_SIGNING_REQUIRED=NO && brew install fbsimctl --HEAD` worked for me. I'll run the risk of having acceptance tests that use an unstable version of fbsimctl for now. You can make the same decision for yourself. I hope this helps you.

**Comment by rjanjua** [comment]
I did the following as @pachun explained: 

`export CODE_SIGNING_REQUIRED=NO && brew install fbsimctl --HEAD `

It worked for a day, but now it's failing again.

**Comment by MoOx** [comment]
Got the same issue, using HEAD didn't help as I am using macOS 10.13 (and homebrew is yelling with xcode version etc).
I pushed a fix in facebook/fb tap to fix the sha as the actual is good.

https://github.com/facebook/homebrew-fb/pull/19

That said if you use macOS 10.13 beta, this don't help.

**Comment by MoOx** [comment]
For macOS 10.13 beta users (and until Xcode 9 is supported) see workaround here https://github.com/facebook/FBSimulatorControl/issues/435#issuecomment-329522823

**Comment by buskerone** [comment]
Same problem here, but it works using HEAD.
macOS 10.12.5
Homebrew 1.3.3
Homebrew/homebrew-core (git revision 55372; last commit 2017-09-24)

**Comment by Dupleks** [comment]
@MoOx any updates on your pull request? Still facing the issue. Thanks

**Comment by MoOx** [comment]
Can be closed since https://github.com/facebook/homebrew-fb/commit/558e6ed3407f8d205bd509bc59b8a02b1ef2b2df

**Comment by MoOx** [comment]
Can be closed (fixed by https://github.com/facebook/homebrew-fb/commit/558e6ed3407f8d205bd509bc59b8a02b1ef2b2df)
